version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-devops-network

volumes:
  postgres_data:

networks:
  api-devops-network:
    driver: bridge
